<a href="https://colab.research.google.com/github/ishahmshah1025/IEEE-HACKATHON-Data-Pioneers/blob/main/Data_Pioneers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import pandas as pd
import numpy as np

In [37]:
pd.read_csv("/content/cardekho_dataset.csv")

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [38]:
cars = pd.read_csv("/content/cardekho_dataset.csv")

Data Cleaning

In [39]:
cars.duplicated().sum()

0

there are no duplicate values in the dataset

In [40]:
cars.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

there are no null values in the dataset

In [41]:
cars.drop(labels=['car_name','max_power','Unnamed: 0'],axis=1,inplace=True)

cars

,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,seats,selling_price
0,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,5,120000
1,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,5,550000
2,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,5,215000
3,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,5,226000
4,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,5,570000
...,...,...,...,...,...,...,...,...,...,...,...
15406,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,5,250000
15407,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,7,925000
15408,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,5,425000
15409,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,7,1225000
15410,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,5,1200000

Data Visualization

In [44]:
cars.describe(include='all')

,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,seats,selling_price
count,15411,15411,15411.000000,1.541100e+04,15411,15411,15411,15411.000000,15411.000000,15411.000000,1.541100e+04
unique,32,120,NaN,NaN,3,5,2,NaN,NaN,NaN,NaN
top,Maruti,i20,NaN,NaN,Dealer,Petrol,Manual,NaN,NaN,NaN,NaN
freq,4992,906,NaN,NaN,9539,7643,12225,NaN,NaN,NaN,NaN
mean,NaN,NaN,6.036338,5.561648e+04,NaN,NaN,NaN,19.701151,1486.057751,5.325482,7.749711e+05
std,NaN,NaN,3.013291,5.161855e+04,NaN,NaN,NaN,4.171265,521.106696,0.807628,8.941284e+05
min,NaN,NaN,0.000000,1.000000e+02,NaN,NaN,NaN,4.000000,793.000000,0.000000,4.000000e+04
25%,NaN,NaN,4.000000,3.000000e+04,NaN,NaN,NaN,17.000000,1197.000000,5.000000,3.850000e+05
50%,NaN,NaN,6.000000,5.000000e+04,NaN,NaN,NaN,19.670000,1248.000000,5.000000,5.560000e+05
75%,NaN,NaN,8.000000,7.000000e+04,NaN,NaN,NaN,22.700000,1582.000000,5.000000,8.250000e+05
max,NaN,NaN,29.000000,3.800000e+06,NaN,NaN,NaN,33.540000,6592.000000,9.000000,3.950000e+07

In [46]:
cars.head()

,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,seats,selling_price
0,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,5,120000
1,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,5,550000
2,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,5,215000
3,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,5,226000
4,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,5,570000